### ISSUE TITLE
SessionNotCreatedException when running `:TOpng`

### ISSUE THREAD

**Issue by chaudum** [JMcKiern/vim-shoot#3]
**Environment**

```console
$ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

$ uname -a
Linux technics1210 5.7.0-3-amd64 #1 SMP Debian 5.7.17-1 (2020-08-23) x86_64 GNU/Linux

$ /usr/local/firefox/firefox --version
Mozilla Firefox 81.0b4
```
The plugin installed correctly, also the post-install hook finished with OK when running `PlugInstall` (with `geckodriver`).

However, when selecting a few lines and running `:TOpng` I get the following error:

**Steps to reproduce**

```
Error detected while processing function shoot#Shoot[21]..provider#python3#Call:                                                                                                                          
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/shoot.py", line 34, in Html2Png
    driver = driver_mgr.GetDriver()
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 68, in GetDriver
    driver = GetDriverLocal()
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 53, in GetDriverLocal
    return CreateDriver(path)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 33, in CreateDriver
    driver = webdriver.Firefox(executable_path=path,
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by chaudum** [comment]
I found this issue https://github.com/mozilla/geckodriver/issues/1488#issuecomment-459745448 so I added the `firefox_binary=`argument to the `webdriver.Firefox()` instantiation, which solve the problem:

```python
        driver = webdriver.Firefox(
            firefox_binary='/usr/local/firefox/firefox-bin',
            executable_path=path,
            log_path=log_path,
            options=options,
        )
```

**Comment by JMcKiern** [comment]
I can replicate the issue using the 0.27 release of geckodriver. Using 0.26 works fine for me.

If I use `firefox_binary='/usr/bin/firefox'` it doesn't work. But pointing to the actual binary (`firefox_binary='/lib/firefox/firefox'`) does work. 

There's also `webdriver.firefox.firefox_binary.FirefoxBinary()` in selenium
 that could be used but unfortunately this only points to the symlink and therefore doesn't work.

I'll keep looking and see if I can find any nice fix

**Comment by chaudum** [comment]
> I'll keep looking and see if I can find any nice fix

What do you think about a plugin setting `firefox_binary`, that can be set for non-standard Firefox installations?

**Comment by JMcKiern** [comment]
Ok, I think I've found it. A change made for 0.27 introduced an error which trigged if firefox is run from a shell script AND the `desiredCapabilites` flag `acceptInsecureCerts` is True (which seems to be the default for selenium).

Some relevant links:
https://bugzilla.mozilla.org/show_bug.cgi?id=1658870
https://github.com/mozilla/geckodriver/issues/1756#issuecomment-672760345

It seems that this bug can be avoided by setting acceptInsecureCerts to False. 
I have made a pr with the change, would you mind testing it on your machine if you get a chance?

**Comment by chaudum** [comment]
Using the fix solves only half of the problem:

Instead of `Unable to find a matching set of capabilities`, the exception message is now `Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`. I still need to set the `firefox_binary` argument to make it work.

```
Error detected while processing function shoot#Shoot[21]..provider#python3#Call:                                                                                                                          
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/shoot.py", line 34, in Html2Png
    driver = driver_mgr.GetDriver()
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 69, in GetDriver
    driver = GetDriverLocal()
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 54, in GetDriverLocal
    return CreateDriver(path)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 34, in CreateDriver
    driver = webdriver.Firefox(executable_path=path,
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/christian/.local/share/nvim/plugged/vim-shoot/3rdparty/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

**Comment by JMcKiern** [comment]
Ok, thanks for letting me know.

Is it correct to assume that you don't have firefox on your PATH?

Either way, I have added `g:shoot_browser_binary` to the `geckodriver-workaround` branch.

`let g:shoot_browser_binary = '/usr/local/firefox/firefox'` should work for you.

Could you check if this fixes your problem please?

**Comment by chaudum** [comment]
> Ok, thanks for letting me know.
> 
> Is it correct to assume that you don't have firefox on your PATH?

Yes, that is correct. I have a `Firefox.desktop` file instead.

> Either way, I have added `g:shoot_browser_binary` to the `geckodriver-workaround` branch.
> 
> `let g:shoot_browser_binary = '/usr/local/firefox/firefox'` should work for you.
> 
> Could you check if this fixes your problem please?

Works like a charm!

**Comment by JMcKiern** [comment]
Great! I'll merge that PR. Thanks for your help!
