### ISSUE TITLE
Problem when using packer in Neovim with lua

### ISSUE THREAD

**Issue by Yoliani** [JMcKiern/vim-shoot#6]
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/edgardoyoliani/.local/share/nvim/site/pack/packer/start/vim-shoot/lib/shoot.py", line 34, in Html2Png
    driver = driver_mgr.GetDriver(browser_binary)
  File "/home/edgardoyoliani/.local/share/nvim/site/pack/packer/start/vim-shoot/lib/driver_mgr.py", line 75, in GetDriver
    raise RuntimeError("Could not find a supported webdriver. See https://github.com/jmckiern/vim-shoot for details.")
RuntimeError: Could not find a supported webdriver. See https://github.com/jmckiern/vim-shoot for details.

I am using 
use 'jmckiern/vim-shoot'

**Comment by JMcKiern** [comment]
Shoot is unable to find a webdriver. Do you have one installed?

You can install one manually or by using install.py (eg `Plug 'jmckiern/vim-shoot', { 'do': '\"./install.py\" chromedriver' }`).

**Comment by Yoliani** [comment]
Went to the ~/.local/share/nvim/site/pack/packer/packer/start/vim-shoot folder and run install.py
Thanks man!!!
